site_name: Wiki
site_author: Shant Ergenian

repo_url: https://github.com/tnahs/dotfiles/
repo_name: tnahs/dotfiles
edit_uri: ""

copyright: Copyright &copy; 2020 Shant Ergenian

theme:
  name: material
  palette:
    primary: teal
  features:
    - navigation.tabs
    - navigation.instant

nav:
  - Python:
    - python/01-install-poetry.md
    - python/02-install-pyenv.md
    - python/03-create-a-project.md
    - python/04-setup-vscode.md
    - python/05-testing-and-coverage.md
    - python/06-publish-to-pypi.md
  - macOS:
    - macos/restore-applebooks.md
    - macos/export-contacts.md
    - macos/sparsebundles.md
    - macos/references.md
    # - macos/privacy.md
  - git:
    - git/01-create-a-new-repo.md
  - Synology:
    - synology/01-router.md
    - synology/02-network.md
    - synology/03-data.md
    - synology/04-extras.md
    - synology/05-reference.md
  - Recipes:
    - recipes/sourdough-starter/index.md
    - recipes/sourdough-bread/index.md
    - recipes/alton-browns-ginger-snaps-cookies/index.md
    - recipes/braised-eggs-with-leek-and-zaatar-aka-green-shakshuka/index.md
    - recipes/braised-eggs-with-beef-smoked-aubergine-and-tomato/index.md
    - recipes/empanadas-con-queso/index.md


markdown_extensions:
  - footnotes
  - markdown.extensions.admonition
  - markdown.extensions.smarty
  - markdown.extensions.def_list
  - markdown.extensions.toc:
      permalink: true
      toc_depth: 3
  - pymdownx.mark
  - pymdownx.keys
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
