site_name: Wiki
site_author: Shant Ergenian

theme:
  name: material
  palette:
    - scheme: slate
      toggle:
        icon: material/eye-outline
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/eye
        name: Switch to dark mode
  font:
    code: JetBrains Mono
  features:
    - navigation.tabs
    - navigation.instant
  extra_css:
    - assets/stylesheets/fonts.css

nav:
  - Python:
      - python/install-poetry.md
      - python/install-pyenv.md
      - python/create-a-project.md
      - python/setup-vscode.md
      - python/publish-to-pypi.md
  - macOS:
      - macos/apple-books-library.md
      - macos/apple-symbolic-hotkeys.md
      - macos/misc.md
      - macos/reference.md
      - macos/ssh.md
  - Synology:
      - synology/router.md
      - synology/dsm.md
      - synology/network.md
      - synology/data.md
      - synology/reference.md
      # - synology/extras.md
  - Recipes:
      - recipes/sourdough-starter/index.md
      - recipes/sourdough-bread/index.md
      - recipes/pizza-dough/index.md
      - recipes/pizza-sauce/index.md
      - recipes/alton-browns-ginger-snaps-cookies/index.md
      - recipes/alton-browns-oatmeal-banana-bread/index.md
      - recipes/green-shakshuka/index.md
      - recipes/arepas-rellenas/index.md
      - recipes/reina-pepiada/index.md
      # - recipes/empanadas-con-queso/index.md

markdown_extensions:
  - footnotes
  - markdown.extensions.admonition
  - markdown.extensions.smarty
  - markdown.extensions.def_list
  - markdown.extensions.toc:
      permalink: true
      toc_depth: 3
  - pymdownx.mark
  - pymdownx.keys
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
