site_name: Wiki
site_author: Shant Ergenian

copyright: Copyright &copy; 2020 Shant Ergenian

theme:
  name: material
  palette:
    primary: deep purple
  features:
    - navigation.tabs
    - navigation.instant

nav:
  - Python:
    - python/install-poetry.md
    - python/install-pyenv.md
    - python/create-a-project.md
    - python/setup-vscode.md
    - python/testing-and-coverage.md
    - python/publish-to-pypi.md
  - macOS:
    - macos/misc.md
    - macos/apple-books.md
    - macos/apple-symbolic-hotkeys.md
    - macos/reference.md
  # - git:
    # - git/01-create-a-new-repo.md
  - Synology:
    - synology/router.md
    - synology/dsm.md
    - synology/network.md
    - synology/data.md
    - synology/extras.md
    - synology/reference.md
  - Recipes:
    - recipes/sourdough-starter/index.md
    - recipes/sourdough-bread/index.md
    - recipes/alton-browns-ginger-snaps-cookies/index.md
    # - recipes/braised-eggs-with-leek-and-zaatar-aka-green-shakshuka/index.md
    # - recipes/braised-eggs-with-beef-smoked-aubergine-and-tomato/index.md
    # - recipes/empanadas-con-queso/index.md


markdown_extensions:
  - footnotes
  - markdown.extensions.admonition
  - markdown.extensions.smarty
  - markdown.extensions.def_list
  - markdown.extensions.toc:
      permalink: true
      toc_depth: 3
  - pymdownx.mark
  - pymdownx.keys
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
